### ISSUE TITLE
Cannot render a dashboard

### ISSUE THREAD

**Issue by mariano80** [wojciechka/influxdb-dashboard-renderer#2]
Hi!
 I'm trying to use the python script in the REAMD and the server and in both caes i have the same error. My main goal is export the dashboard to make a pdf report.

Below the output of script and the server usage. Any help would be appreciated

Error in server stdout
-----------------------

[2021-08-06 19:58:24,233] ERROR in app: Exception on /render [POST]
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib64/python3.6/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "./server/server.py", line 87, in render
    result = get_dashboard_from_request()
  File "./server/server.py", line 49, in get_dashboard_from_request
    d = InfluxDBDashboardView(c, dashboard_id)
  File "/home/user/influxdb-dashboard-renderer/influxdb_dashboard/client.py", line 214, in __init__
    self.name = info.name
AttributeError: 'dict' object has no attribute 'name'
127.0.0.1 - - [06/Aug/2021 19:58:24] "POST /render HTTP/1.1" 500 -

** Curl Command ** 

[root@server influxdb-dashboard-renderer] curl --header "Content-Type: application/json" -X POST \
> --data '{^
>   "url": "http://10.x.x.x:8086",
>   "token": "token_id_created_in_influx",
>   "org_id": "organization_id_taken_from_about_section",
>   "id": "id_of_the_dashboard",
>   "width": 1280,
>   "height": 720,
>   "dpi": 75
> }' http://127.0.0.1:5000/render
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
[root@silenox influxdb-dashboard-renderer]# 

Error in script
---------------

Traceback (most recent call last):
  File "influx.py", line 9, in <module>
    d = InfluxDBDashboardView.find_by_label(c, LABEL)
  File "/home/user/influxdb-dashboard-renderer/influxdb_dashboard/client.py", line 250, in find_by_label
    return cls(client, matches[0].id, org_id=org_id)
  File "/home/user/influxdb-dashboard-renderer/influxdb_dashboard/client.py", line 214, in __init__
    self.name = info.name
AttributeError: 'dict' object has no attribute 'name'

** Parameter **
TOKEN='token_id_created_in_influx'
ORG_ID='organization_id_taken_from_about_section'
LABEL='name_of_the_label_asociated_with_dashboard'

c = InfluxDBClient(url='http://10.x.x.x:8086', token=TOKEN, org=ORG_ID)

** Aditional note **
I found and error in script about the import. I use this:

from influxdb_dashboard import InfluxDBDashboardView, InfluxDBDashboardOutput
from influxdb_client import InfluxDBClient

Regards,
Mariano

**Comment by wojciechka** [comment]
The code that fails is this:

https://github.com/wojciechka/influxdb-dashboard-renderer/blob/e983092/influxdb_dashboard/client.py#L213-L214
```
    info = self.ds.get_dashboards_id(self.id)
    self.name = info.name
```

Is it possible your dashboard does not have a name? I'll work on adding support for this and testing it, but perhaps just naming the dashboard would be a good enough workaround for now?

Also, which exact version of InfluxDB are you communicating with?

**Comment by mariano80** [comment]
Hi!

Yes dashboard has a the default name change and the version of Influx that I'm using is "influxdb2-2.0.7.x86_64", the lastest I think.

**Comment by mariano80** [comment]
Hi! Problem was solved with this update.

Regards.
