### ISSUE TITLE
error

### ISSUE THREAD

**Issue by jezzaf** [wojciechka/influxdb-dashboard-renderer#4]
I'v tried to get this working but no mater what I enter I only get 
{"status": "error", "message": "not all arguments were provided"}

I have Token, location, org id set as variables in the docker image

the URL I'm sending is http://192.168.0.11:5000/render?lable=House

thanks

**Comment by ser** [comment]
For me it does not work either.

```
Traceback (most recent call last):
  File "pcps.py", line 21, in <module>
    d = InfluxDBDashboardView(c, 'xxxxxxxxxxxxxx', ORG_ID)
  File "/home/ser/influxdb-dashboard-renderer/influxdb_dashboard/client.py", line 218, in __init__
    self.name = info.get('name', '')
AttributeError: 'DashboardWithViewProperties' object has no attribute 'get'

```

**Comment by ser** [comment]
lable or label?

**Comment by jezzaf** [comment]
my bad sorry about the typo 
not sure how that happened
